# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-30 19:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=70)),
                ('shortIdentifier', models.CharField(max_length=25)),
                ('submissionDatetime', models.DateTimeField(auto_now_add=True)),
                ('userEmail', models.EmailField(max_length=35)),
                ('xml', models.TextField()),
            ],
            options={
                'verbose_name': 'LicenseRequest',
                'verbose_name_plural': 'LicenseRequests',
            },
        ),
        migrations.CreateModel(
            name='UserID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=64, verbose_name='Organisation')),
                ('lastlogin', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Last Login')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
