# Generated by Django 3.2.18 on 2023-05-24 06:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensenamespace',
            name='text',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='text',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
