# Generated by Django 3.2.18 on 2023-03-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensenamespace',
            name='issueId',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='issueId',
            field=models.TextField(default=''),
        ),
    ]
