# Generated by Django 3.2.18 on 2023-07-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensenamespace',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
