# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-02 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseNamespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(default='', max_length=100)),
                ('submitterFullname', models.CharField(max_length=70)),
                ('submitterEmail', models.EmailField(max_length=35)),
                ('url', models.TextField()),
                ('publiclyShared', models.BooleanField(default=True)),
                ('namespace', models.TextField()),
                ('submissionDatetime', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('archive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'LicenseNamespace',
                'verbose_name_plural': 'LicenseNamespaces',
            },
        ),
        migrations.CreateModel(
            name='OrganisationName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('orgId', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'OrganisationName',
                'verbose_name_plural': 'OrganisationNames',
            },
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='licenseAuthorName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='notes',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='licensenamespace',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OrganisationName'),
        ),
    ]
