# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-23 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190723_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensenamespace',
            name='license_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.LicenseRequest'),
        ),
        migrations.AlterField(
            model_name='licensenamespace',
            name='shortIdentifier',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='licenserequest',
            name='shortIdentifier',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
