# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-02 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190602_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensenamespace',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.OrganisationName'),
        ),
    ]
