# Generated by Django 3.2.18 on 2023-07-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230704_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensenamespace',
            name='isException',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='isException',
            field=models.BooleanField(default=True),
        ),
    ]
