# Generated by Django 3.2.18 on 2023-04-01 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230330_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensenamespace',
            name='issueId',
        ),
    ]
