# Generated by Django 3.2.20 on 2024-01-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230727_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensenamespace',
            name='shortIdentifier',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='licenserequest',
            name='shortIdentifier',
            field=models.CharField(max_length=50),
        ),
    ]
