# Generated by Django 3.2.18 on 2023-05-24 16:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230524_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensenamespace',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
