# Generated by Django 3.2.18 on 2023-05-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230524_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensenamespace',
            name='content',
        ),
        migrations.RemoveField(
            model_name='licenserequest',
            name='content',
        ),
    ]
