# Generated by Django 3.2.18 on 2023-05-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230526_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensenamespace',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
