# Generated by Django 2.2.14 on 2020-07-18 10:35

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidateFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=api.models.user_directory_path)),
                ('result', models.CharField(max_length=128)),
                ('status', models.IntegerField(default=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitLicenseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('licenseAuthorName', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('fullname', models.CharField(max_length=70)),
                ('shortIdentifier', models.CharField(max_length=25)),
                ('userEmail', models.EmailField(max_length=35)),
                ('result', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.IntegerField(default=200)),
                ('sourceUrl', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('osiApproved', models.CharField(choices=[(0, '-'), ('Approved', 'Approved'), ('Not Submitted', 'Not Submitted'), ('Pending', 'Submitted, but pending'), ('Rejected', 'Rejected')], default=0, max_length=15)),
                ('comments', models.TextField(blank=True, default='', null=True)),
                ('licenseHeader', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('text', models.TextField(default='')),
                ('xml', models.TextField(default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConvertFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_format', models.CharField(max_length=16)),
                ('to_format', models.CharField(max_length=16)),
                ('tagToRdfFormat', models.CharField(blank=True, max_length=16, null=True)),
                ('cfilename', models.CharField(max_length=32)),
                ('result', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to=api.models.user_directory_path)),
                ('status', models.IntegerField(default=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompareFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=64)),
                ('file1', models.FileField(upload_to=api.models.user_directory_path)),
                ('file2', models.FileField(upload_to=api.models.user_directory_path)),
                ('rfilename', models.CharField(max_length=32)),
                ('status', models.IntegerField(default=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckLicenseFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=api.models.user_directory_path)),
                ('result', models.CharField(max_length=128)),
                ('status', models.IntegerField(default=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
