# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitLicenseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('licenseAuthorName', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('fullname', models.CharField(max_length=70)),
                ('shortIdentifier', models.CharField(max_length=25)),
                ('userEmail', models.EmailField(max_length=35)),
                ('result', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.IntegerField(default=200)),
                ('sourceUrl', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('osiApproved', models.CharField(choices=[(0, '-'), ('Approved', 'Approved'), ('Not Submitted', 'Not Submitted'), ('Pending', 'Submitted, but pending'), ('Rejected', 'Rejected')], default=0, max_length=15)),
                ('comments', models.TextField(blank=True, default='', null=True)),
                ('licenseHeader', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('text', models.TextField(default='')),
                ('xml', models.TextField(default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
