# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUpload',
            new_name='ValidateFileUpload',
        ),
        migrations.RenameField(
            model_name='validatefileupload',
            old_name='datafile',
            new_name='file',
        ),
    ]
