# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170819_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparefileupload',
            name='status',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='convertfileupload',
            name='status',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='validatefileupload',
            name='status',
            field=models.IntegerField(default=200),
        ),
    ]
