# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-04 13:07
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170824_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparefileupload',
            name='file1',
            field=models.FileField(upload_to=api.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='comparefileupload',
            name='file2',
            field=models.FileField(upload_to=api.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='convertfileupload',
            name='file',
            field=models.FileField(upload_to=api.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='validatefileupload',
            name='file',
            field=models.FileField(upload_to=api.models.user_directory_path),
        ),
    ]
