# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_validatefileupload_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convertfileupload',
            old_name='type',
            new_name='from_format',
        ),
        migrations.AddField(
            model_name='convertfileupload',
            name='cfilename',
            field=models.CharField(default='old', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convertfileupload',
            name='to_format',
            field=models.CharField(default='old', max_length=16),
            preserve_default=False,
        ),
    ]
