# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170805_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparefileupload',
            name='rfilename',
            field=models.CharField(default='old', max_length=32),
            preserve_default=False,
        ),
    ]
